targets:
  $default:
    builders:
      generators|annotations:
        enabled: true

builders:
  generators:
    import: "package:theme_generator/theme_generator.dart"
    builder_factories: ["generateTheme"]
    build_extensions: { ".dart": [".theme.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before: ["json_serializable|json_serializable"]