name: theme_generator
description: Package that help to generate theme that behaves like material themes, but with serialization and deserialization.
version: 0.3.0
repository: https://github.com/massa-org/theme_generator

environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies:
  theme_annotation: ^0.3.0
  

  theme_json_converter: ^0.1.0
    
  build: ^2.0.0
  source_gen: ^1.1.0
  analyzer: '>=2.0.0 <6.0.0'

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^2.0.0


  
