name: theme_generator
description: Package that help to generate theme that behaves like material themes, but with serialization and deserialization.
version: 0.0.2
homepage: https://github.com/massa-org/theme_generator

environment:
  sdk: ">=2.12.0 <3.0.0"
  
dependencies:
  theme_annotation: ^0.0.1

  theme_json_converter: ^0.0.1
    
  build: ^2.0.0
  source_gen: ^1.0.0
  analyzer: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  pedantic: ^1.11.1
  flutter_lints: ^1.0.0


  
